project_id = "lefmdwcvddkrksggwnad"

[functions.create-booking]
verify_jwt = false

[functions.widget-data]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.validate-ticket]
verify_jwt = false

[functions.generate-terms]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.validate-activity-ticket]
verify_jwt = false
